//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENFrontEnd.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GENEntities : DbContext
    {
        public GENEntities()
            : base("name=GENEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MCOMBO> MCOMBOes { get; set; }
        public virtual DbSet<MEMPLOYEE> MEMPLOYEEs { get; set; }
        public virtual DbSet<MPOSITION> MPOSITIONs { get; set; }
        public virtual DbSet<TREMAIL> TREMAILs { get; set; }
        public virtual DbSet<MBRANCH> MBRANCHes { get; set; }
        public virtual DbSet<TRLOG> TRLOGs { get; set; }
        public virtual DbSet<MCOURSE> MCOURSEs { get; set; }
        public virtual DbSet<MSTUDENT> MSTUDENTs { get; set; }
        public virtual DbSet<SYSTEMHISTORY> SYSTEMHISTORies { get; set; }
        public virtual DbSet<TCOURSE> TCOURSEs { get; set; }
    
        public virtual ObjectResult<SP_GETEMAIL_Result> SP_GETEMAIL(Nullable<int> eMAILID)
        {
            var eMAILIDParameter = eMAILID.HasValue ?
                new ObjectParameter("EMAILID", eMAILID) :
                new ObjectParameter("EMAILID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GETEMAIL_Result>("SP_GETEMAIL", eMAILIDParameter);
        }
    }
}
