//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENFrontEnd.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GENEntities : DbContext
    {
        public GENEntities()
            : base("name=GENEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MCOMBO> MCOMBOes { get; set; }
        public virtual DbSet<MEMPLOYEE> MEMPLOYEEs { get; set; }
        public virtual DbSet<MPOSITION> MPOSITIONs { get; set; }
        public virtual DbSet<TREMAIL> TREMAILs { get; set; }
        public virtual DbSet<MBRANCH> MBRANCHes { get; set; }
    }
}
