//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENFrontEnd.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMPLOYEE
    {
        public string EmployeeId { get; set; }
        public string UserId { get; set; }
        public string Password { get; set; }
        public string EmployeeName { get; set; }
        public string Position { get; set; }
        public string Supercoordinate { get; set; }
        public string Gender { get; set; }
        public Nullable<int> BranchID { get; set; }
        public string PublicEmail { get; set; }
        public string OfficeEmail { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<int> Active { get; set; }
        public string Photo { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Phone { get; set; }
        public string Phone2 { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
    }
}
