//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENFrontEnd.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPOSITION
    {
        public string IdPosition { get; set; }
        public string PositionName { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
