//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENFrontEnd.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TREMAIL
    {
        public long EmailID { get; set; }
        public string SenderFullName { get; set; }
        public string SenderPhone { get; set; }
        public string SenderEmail { get; set; }
        public string SenderQuestion { get; set; }
        public string SenderIP { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> IsReply { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ReplyDate { get; set; }
        public string ReplyMessage { get; set; }
        public string EmailCategory { get; set; }
    }
}
